name: Deploy MakeDungeon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site-tools-makeDungeon
        uses: actions/checkout@v4

      - name: Deploy para /tools/makeDungeon
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: le314u/le314u.github.io
          publish_branch: prod
          publish_dir: .
          destination_dir: tools/makeDungeon
